from enum import Enum


class WeaponCategory(str, Enum):
    DAGGER = 'dagger'
    STRAIGHT_SWORD = 'straight_sword'
    GREATSWORD = 'greatsword'
    ULTRA_GREATSWORD = 'ultra_greatsword'
    CURVED_SWORD = 'curved_sword'
    CURVED_GREATSWORD = 'curved_greatsword'
    THRUSTING_SWORD = 'thrusting_sword'
    KATANA = 'katana'
    AXE = 'axe'
    GREATAXE = 'greataxe'
    HAMMER = 'hammer'
    GREATHAMMER = 'greathammer'
    SPEAR = 'spear'
    HALBERD = 'halberd'
    PIKE = 'pike'
    REAPER = 'reaper'
    WHIP = 'whip'
    FIST = 'fist'
    CLAW = 'claw'
    TORCH = 'torch'
    BOW = 'bow'
    GREATBOW = 'greatbow'
    CROSSBOW = 'crossbow'
    STAFF = 'staff'
    TALISMAN = 'talisman'
    PYROMANCY_FLAME = 'pyromancy_flame'
    SACRED_CHIME = 'sacred_chime'
